# K39 WiFi setup Jan 2024
SSID = "2G"
PASSWORD = "Ming@l@b@r39"
USER = "Eric8266"
REPOSITORY = "OTA-SENKO"
BRANCH = "main"
GITHUB_URL = "https://github.com"
GITHUB_RAW_URL = "https://raw.githubusercontent.com"
FILES = "test1.py", "test2.py"
REMOTE_UPDATE = "YES"